#!/usr/bin/env bash

# Bare-metal helper script: run Open-A2A Bridge (and optional Relay)
# on the same server where OpenClaw is running, **without** Docker.
#
# Usage:
#   1) Clone this repo on the OpenClaw server
#   2) cd Open-A2A
#   3) bash scripts/setup-openclaw-bridge-baremetal.sh
#   4) Follow prompts for NATS_URL / OPENCLAW_GATEWAY_URL / OPENCLAW_HOOKS_TOKEN
#
# Requirements:
#   - python3 / make are installed
#   - NATS server is reachable from this machine (or will be started separately)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="$ROOT_DIR/.env"
VENV_DIR=".venv"

echo "== Open-A2A / OpenClaw bare-metal bridge helper =="
echo

if ! command -v python3 >/dev/null 2>&1; then
  echo "[error] python3 not found. Please install Python 3.9+ on this server."
  exit 1
fi

if ! command -v make >/dev/null 2>&1; then
  echo "[error] make not found. Please install make (build-essential) and retry."
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  echo "[info] Found existing .env, will append/update key variables."
else
  echo "[info] No .env found, creating from .env.example."
  cp .env.example .env
fi

echo
read -rp "Enter NATS_URL (default nats://localhost:4222): " INPUT_NATS_URL
NATS_URL_VALUE="${INPUT_NATS_URL:-nats://localhost:4222}"

read -rp "Enter OpenClaw Gateway URL (e.g. http://localhost:18789): " INPUT_GATEWAY
OPENCLAW_GATEWAY_URL_VALUE="${INPUT_GATEWAY:-http://localhost:18789}"

read -rp "Enter OpenClaw hooks token: " INPUT_TOKEN
OPENCLAW_HOOKS_TOKEN_VALUE="${INPUT_TOKEN:-}"

echo
echo "[info] Will append to .env:"
echo "  NATS_URL=$NATS_URL_VALUE"
echo "  OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
echo "  OPENCLAW_HOOKS_TOKEN=[provided]"
echo

{
  echo ""
  echo "# === Auto-generated by scripts/setup-openclaw-bridge-baremetal.sh ==="
  echo "NATS_URL=$NATS_URL_VALUE"
  echo "OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
  echo "OPENCLAW_HOOKS_TOKEN=$OPENCLAW_HOOKS_TOKEN_VALUE"
} >> "$ENV_FILE"

echo "[info] Updated $ENV_FILE"
echo

echo "[info] Creating virtualenv and installing bridge dependencies via make ..."
make install-bridge

BRIDGE_PORT="${BRIDGE_PORT:-8080}"

echo
echo "[info] Starting Open-A2A Bridge in background (bare-metal) ..."
mkdir -p logs
nohup "$VENV_DIR/bin/uvicorn" bridge.main:app --host 0.0.0.0 --port "$BRIDGE_PORT" > logs/bridge.log 2>&1 &
BRIDGE_PID=$!

echo "[done] Bridge started as PID $BRIDGE_PID on port $BRIDGE_PORT."
echo "       Logs: $(pwd)/logs/bridge.log"
echo
echo "Next steps in OpenClaw:"
echo "  - Configure a Tool that calls the Bridge at ${OPENCLAW_GATEWAY_URL_VALUE%:*}:$BRIDGE_PORT/api/publish_intent"
echo "  - Configure a webhook at $OPENCLAW_GATEWAY_URL_VALUE/hooks/agent with the provided token"
echo "  - See docs/en/openclaw-tool-example.md or docs/zh/openclaw-tool-example.md for Tool + Hook details."

