#!/usr/bin/env bash

# Simple helper script: start Open-A2A Bridge + NATS + Relay + Solid
# on the same server where OpenClaw is running.
#
# Usage:
#   1) Clone this repo on the OpenClaw server
#   2) cd Open-A2A
#   3) bash scripts/setup-openclaw-bridge.sh
#   4) Enter NATS_URL / OPENCLAW_GATEWAY_URL / OPENCLAW_HOOKS_TOKEN when prompted
#
# Requirements:
#   - docker and docker-compose are installed
#   - OpenClaw Gateway is reachable from this machine

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="$ROOT_DIR/.env"
COMPOSE_FILE="$ROOT_DIR/deploy/quickstart/docker-compose.full.yml"

detect_compose() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
    return 0
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
    return 0
  fi
  echo ""
  return 1
}

detect_gateway_default() {
  # 优先：尝试通过容器名中带 gateway 的容器自动推断
  local cid name
  cid="$(docker ps --filter "name=gateway" --format '{{.ID}}' | head -n 1 || true)"
  if [[ -n "${cid:-}" ]]; then
    name="$(docker inspect "$cid" --format '{{.Name}}' 2>/dev/null | sed 's#^/##')"
    if [[ -n "${name:-}" ]]; then
      echo "http://${name}:18789"
      return 0
    fi
  fi
  # 兜底：留空，让后续交互使用示例值
  echo ""
}

diagnose() {
  echo "== Open-A2A / OpenClaw integration diagnose =="
  echo

  if [[ ! -f "$ENV_FILE" ]]; then
    echo "[warn] .env not found at $ENV_FILE"
  else
    echo "[info] .env found, current related variables:"
    grep -E "NATS_URL|OPENCLAW_GATEWAY_URL|OPENCLAW_HOOKS_TOKEN" "$ENV_FILE" || echo "  (no matching keys)"
  fi

  echo
  echo "[step] Checking Bridge container environment (if running)..."
  if docker ps --format '{{.Names}}' | grep -q '^open-a2a-open-a2a-bridge-1$'; then
    docker exec open-a2a-open-a2a-bridge-1 env | grep -E "NATS_URL|OPENCLAW_GATEWAY_URL|OPENCLAW_HOOKS_TOKEN" || echo "  (no env vars found in container)"
  else
    echo "[warn] Bridge container open-a2a-open-a2a-bridge-1 not running."
  fi

  echo
  echo "[step] Checking connectivity to OpenClaw Gateway from host..."
  if grep -q "OPENCLAW_GATEWAY_URL" "$ENV_FILE" 2>/dev/null; then
    GATEWAY_URL="$(grep "OPENCLAW_GATEWAY_URL" "$ENV_FILE" | tail -n1 | cut -d'=' -f2-)"
    echo "  Using OPENCLAW_GATEWAY_URL from .env: $GATEWAY_URL"
    curl -sS -o /dev/null -w "  HTTP status: %{http_code}\n" "${GATEWAY_URL}/" || echo "  [warn] curl to ${GATEWAY_URL}/ failed"
  else
    echo "  [warn] OPENCLAW_GATEWAY_URL not set in .env, skip host curl check."
  fi

  echo
  echo "[step] Checking Bridge API on host (http://localhost:8080)..."
  curl -sS -o /dev/null -w "  /health status: %{http_code}\n" "http://localhost:8080/health" || echo "  [warn] /health not available, try /api/publish_intent manually."

  echo
  echo "[done] Diagnose finished. See warnings above for potential misconfigurations."
}

main() {
  local cmd="${1:-run}"

  case "$cmd" in
    diagnose)
      diagnose
      return 0
      ;;
    run|*)
      ;;
  esac

  echo "== Open-A2A / OpenClaw integration helper =="
  echo

  if [[ -f "$ENV_FILE" ]]; then
    echo "[info] Found existing .env, will append/update key variables."
  else
    echo "[info] No .env found, creating from .env.example."
    cp .env.example .env
  fi

  echo
  read -rp "Enter NATS_URL (default nats://nats:4222): " INPUT_NATS_URL
  NATS_URL_VALUE="${INPUT_NATS_URL:-nats://nats:4222}"

  # 自动探测 OpenClaw Gateway 容器名，提供更合理的默认值
  AUTO_GATEWAY_URL="$(detect_gateway_default)"
  GATEWAY_DEFAULT_HINT="${AUTO_GATEWAY_URL:-http://localhost:3000}"
  echo "[info] Detected default OpenClaw Gateway URL: ${AUTO_GATEWAY_URL:-<none, fallback to example>}"
  read -rp "Enter OpenClaw Gateway URL (default ${GATEWAY_DEFAULT_HINT}): " INPUT_GATEWAY
  OPENCLAW_GATEWAY_URL_VALUE="${INPUT_GATEWAY:-$GATEWAY_DEFAULT_HINT}"

  read -rp "Enter OpenClaw hooks token: " INPUT_TOKEN
  OPENCLAW_HOOKS_TOKEN_VALUE="${INPUT_TOKEN:-}"

  echo
  echo "[info] Will append to .env:"
  echo "  NATS_URL=$NATS_URL_VALUE"
  echo "  OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
  echo "  OPENCLAW_HOOKS_TOKEN=[provided]"
  echo

  {
    echo ""
    echo "# === Auto-generated by scripts/setup-openclaw-bridge.sh ==="
    echo "NATS_URL=$NATS_URL_VALUE"
    echo "OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
    echo "OPENCLAW_HOOKS_TOKEN=$OPENCLAW_HOOKS_TOKEN_VALUE"
  } >> "$ENV_FILE"

  echo "[info] Updated $ENV_FILE"
  echo

  # 3. Use docker-compose to bring up the full stack
  local compose_bin
  compose_bin="$(detect_compose || true)"
  if [[ -z "${compose_bin:-}" ]]; then
    echo "[error] docker compose not found (need Docker Compose v2 or docker-compose)"
    exit 1
  fi
  echo "[info] Starting NATS + Relay + Solid + Bridge via compose ..."
  echo "  Compose file: $COMPOSE_FILE"
  $compose_bin -f "$COMPOSE_FILE" up -d --build

  echo
  echo "[done] Compose started, current container status:"
  docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "open-a2a|nats|solid" || true

  echo
  echo "Next steps in OpenClaw:"
  echo "  - Configure a Tool that calls the Bridge at /api/publish_intent"
  echo "  - Configure a webhook at $OPENCLAW_GATEWAY_URL_VALUE/hooks/agent with the provided token"
  echo "  - See docs/en/openclaw-tool-example.md or docs/zh/openclaw-tool-example.md for Tool + Hook details."
}

main "${1:-run}"
