#!/usr/bin/env bash

# Simple helper script: start Open-A2A Bridge + NATS + Relay + Solid
# on the same server where OpenClaw is running.
#
# Usage:
#   1) Clone this repo on the OpenClaw server
#   2) cd Open-A2A
#   3) bash scripts/setup-openclaw-bridge.sh
#   4) Enter NATS_URL / OPENCLAW_GATEWAY_URL / OPENCLAW_HOOKS_TOKEN when prompted
#
# Requirements:
#   - docker and docker-compose are installed
#   - OpenClaw Gateway is reachable from this machine

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="$ROOT_DIR/.env"

echo "== Open-A2A / OpenClaw integration helper =="
echo

if [[ -f "$ENV_FILE" ]]; then
  echo "[info] Found existing .env, will append/update key variables."
else
  echo "[info] No .env found, creating from .env.example."
  cp .env.example .env
fi

echo
read -rp "Enter NATS_URL (default nats://nats:4222): " INPUT_NATS_URL
NATS_URL_VALUE="${INPUT_NATS_URL:-nats://nats:4222}"

read -rp "Enter OpenClaw Gateway URL (e.g. http://localhost:3000): " INPUT_GATEWAY
OPENCLAW_GATEWAY_URL_VALUE="${INPUT_GATEWAY:-http://localhost:3000}"

read -rp "Enter OpenClaw hooks token: " INPUT_TOKEN
OPENCLAW_HOOKS_TOKEN_VALUE="${INPUT_TOKEN:-}"

echo
echo "[info] Will append to .env:"
echo "  NATS_URL=$NATS_URL_VALUE"
echo "  OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
echo "  OPENCLAW_HOOKS_TOKEN=[provided]"
echo

{
  echo ""
  echo "# === Auto-generated by scripts/setup-openclaw-bridge.sh ==="
  echo "NATS_URL=$NATS_URL_VALUE"
  echo "OPENCLAW_GATEWAY_URL=$OPENCLAW_GATEWAY_URL_VALUE"
  echo "OPENCLAW_HOOKS_TOKEN=$OPENCLAW_HOOKS_TOKEN_VALUE"
} >> "$ENV_FILE"

echo "[info] Updated $ENV_FILE"
echo

# 3. Use docker-compose to bring up the full stack
echo "[info] Starting NATS + Relay + Solid + Bridge via docker-compose ..."
docker-compose -f docker-compose.deploy.yml up -d --build

echo
echo "[done] Compose started, current container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "open-a2a|nats|solid" || true

echo
echo "Next steps in OpenClaw:"
echo "  - Configure a Tool that calls the Bridge at /api/publish_intent"
echo "  - Configure a webhook at $OPENCLAW_GATEWAY_URL/hooks/agent with the provided token"
echo "  - See docs/en/openclaw-tool-example.md or docs/zh/openclaw-tool-example.md for Tool + Hook details."


